// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8569bd2272c8bbd2ffe4aeaedf34bced13dcf39577f92a8edc929d7dbdb37047'>;
export type ExecutionHash =
  ExecutionHashBase<'dc5e9e883d01c1cc9d4f599725b509fdfe10c3894933b7e5cefe77d74993ef84'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Cidade: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lat: CodecTypes['pg/numeric@1']['output'] | null;
      readonly lng: CodecTypes['pg/numeric@1']['output'] | null;
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly uf: CodecTypes['pg/text@1']['output'];
    };
    readonly Compra: {
      readonly comprador: CodecTypes['pg/text@1']['output'] | null;
      readonly comprimentoCm: CodecTypes['pg/int4@1']['output'] | null;
      readonly contatoId: CodecTypes['pg/uuid@1']['output'];
      readonly cor: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly dataCorte: CodecTypes['pg/date-temporal@1']['output'];
      readonly dataRevenda: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly formaPagamento: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly pesoG: CodecTypes['pg/int4@1']['output'] | null;
      readonly quimica: CodecTypes['pg/text@1']['output'] | null;
      readonly textura: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly valorPago: CodecTypes['pg/numeric@1']['output'];
      readonly valorRevenda: CodecTypes['pg/numeric@1']['output'] | null;
    };
    readonly Contato: {
      readonly cicloRecompraMeses: CodecTypes['pg/int4@1']['output'];
      readonly cidadeId: CodecTypes['pg/uuid@1']['output'];
      readonly comprimentoCm: CodecTypes['pg/int4@1']['output'] | null;
      readonly cor: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly deletedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly endereco: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly motivoPerda: CodecTypes['pg/text@1']['output'] | null;
      readonly natural: CodecTypes['pg/bool@1']['output'] | null;
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly observacoes: CodecTypes['pg/text@1']['output'] | null;
      readonly origem: CodecTypes['pg/text@1']['output'] | null;
      readonly quimica: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly textura: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Foto: {
      readonly contatoId: CodecTypes['pg/uuid@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ordem: CodecTypes['pg/int4@1']['output'];
      readonly thumbUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly tipo: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly url: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Cidade: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lat: CodecTypes['pg/numeric@1']['input'] | null;
      readonly lng: CodecTypes['pg/numeric@1']['input'] | null;
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly uf: CodecTypes['pg/text@1']['input'];
    };
    readonly Compra: {
      readonly comprador: CodecTypes['pg/text@1']['input'] | null;
      readonly comprimentoCm: CodecTypes['pg/int4@1']['input'] | null;
      readonly contatoId: CodecTypes['pg/uuid@1']['input'];
      readonly cor: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly dataCorte: CodecTypes['pg/date-temporal@1']['input'];
      readonly dataRevenda: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly formaPagamento: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly pesoG: CodecTypes['pg/int4@1']['input'] | null;
      readonly quimica: CodecTypes['pg/text@1']['input'] | null;
      readonly textura: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly valorPago: CodecTypes['pg/numeric@1']['input'];
      readonly valorRevenda: CodecTypes['pg/numeric@1']['input'] | null;
    };
    readonly Contato: {
      readonly cicloRecompraMeses: CodecTypes['pg/int4@1']['input'];
      readonly cidadeId: CodecTypes['pg/uuid@1']['input'];
      readonly comprimentoCm: CodecTypes['pg/int4@1']['input'] | null;
      readonly cor: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly deletedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly endereco: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly motivoPerda: CodecTypes['pg/text@1']['input'] | null;
      readonly natural: CodecTypes['pg/bool@1']['input'] | null;
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly observacoes: CodecTypes['pg/text@1']['input'] | null;
      readonly origem: CodecTypes['pg/text@1']['input'] | null;
      readonly quimica: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly textura: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Foto: {
      readonly contatoId: CodecTypes['pg/uuid@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ordem: CodecTypes['pg/int4@1']['input'];
      readonly thumbUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly tipo: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly url: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly cidades: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lat: CodecTypes['pg/numeric@1']['output'] | null;
      readonly lng: CodecTypes['pg/numeric@1']['output'] | null;
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly uf: CodecTypes['pg/text@1']['output'];
    };
    readonly compras: {
      readonly comprador: CodecTypes['pg/text@1']['output'] | null;
      readonly comprimento_cm: CodecTypes['pg/int4@1']['output'] | null;
      readonly contato_id: CodecTypes['pg/uuid@1']['output'];
      readonly cor: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly data_corte: CodecTypes['pg/date-temporal@1']['output'];
      readonly data_revenda: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly forma_pagamento: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly peso_g: CodecTypes['pg/int4@1']['output'] | null;
      readonly quimica: CodecTypes['pg/text@1']['output'] | null;
      readonly textura: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly valor_pago: CodecTypes['pg/numeric@1']['output'];
      readonly valor_revenda: CodecTypes['pg/numeric@1']['output'] | null;
    };
    readonly contatos: {
      readonly ciclo_recompra_meses: CodecTypes['pg/int4@1']['output'];
      readonly cidade_id: CodecTypes['pg/uuid@1']['output'];
      readonly comprimento_cm: CodecTypes['pg/int4@1']['output'] | null;
      readonly cor: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly deleted_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly endereco: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly motivo_perda: CodecTypes['pg/text@1']['output'] | null;
      readonly natural: CodecTypes['pg/bool@1']['output'] | null;
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly observacoes: CodecTypes['pg/text@1']['output'] | null;
      readonly origem: CodecTypes['pg/text@1']['output'] | null;
      readonly quimica: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly textura: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly fotos: {
      readonly contato_id: CodecTypes['pg/uuid@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ordem: CodecTypes['pg/int4@1']['output'];
      readonly thumb_url: CodecTypes['pg/text@1']['output'] | null;
      readonly tipo: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly url: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly cidades: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lat: CodecTypes['pg/numeric@1']['input'] | null;
      readonly lng: CodecTypes['pg/numeric@1']['input'] | null;
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly uf: CodecTypes['pg/text@1']['input'];
    };
    readonly compras: {
      readonly comprador: CodecTypes['pg/text@1']['input'] | null;
      readonly comprimento_cm: CodecTypes['pg/int4@1']['input'] | null;
      readonly contato_id: CodecTypes['pg/uuid@1']['input'];
      readonly cor: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly data_corte: CodecTypes['pg/date-temporal@1']['input'];
      readonly data_revenda: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly forma_pagamento: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly peso_g: CodecTypes['pg/int4@1']['input'] | null;
      readonly quimica: CodecTypes['pg/text@1']['input'] | null;
      readonly textura: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly valor_pago: CodecTypes['pg/numeric@1']['input'];
      readonly valor_revenda: CodecTypes['pg/numeric@1']['input'] | null;
    };
    readonly contatos: {
      readonly ciclo_recompra_meses: CodecTypes['pg/int4@1']['input'];
      readonly cidade_id: CodecTypes['pg/uuid@1']['input'];
      readonly comprimento_cm: CodecTypes['pg/int4@1']['input'] | null;
      readonly cor: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly deleted_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly endereco: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly motivo_perda: CodecTypes['pg/text@1']['input'] | null;
      readonly natural: CodecTypes['pg/bool@1']['input'] | null;
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly observacoes: CodecTypes['pg/text@1']['input'] | null;
      readonly origem: CodecTypes['pg/text@1']['input'] | null;
      readonly quimica: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly textura: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly fotos: {
      readonly contato_id: CodecTypes['pg/uuid@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ordem: CodecTypes['pg/int4@1']['input'];
      readonly thumb_url: CodecTypes['pg/text@1']['input'] | null;
      readonly tipo: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly url: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Cidade = {
    id: CodecTypes['pg/uuid@1']['output'];
    lat: CodecTypes['pg/numeric@1']['output'] | null;
    lng: CodecTypes['pg/numeric@1']['output'] | null;
    nome: CodecTypes['pg/text@1']['output'];
    uf: CodecTypes['pg/text@1']['output'];
    contatos: public_Contato[];
    readonly [RelationKeys]?: 'contatos';
  };
  export type public_Compra = {
    comprador: CodecTypes['pg/text@1']['output'] | null;
    comprimentoCm: CodecTypes['pg/int4@1']['output'] | null;
    contatoId: CodecTypes['pg/uuid@1']['output'];
    cor: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    dataCorte: CodecTypes['pg/date-temporal@1']['output'];
    dataRevenda: CodecTypes['pg/date-temporal@1']['output'] | null;
    formaPagamento: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    pesoG: CodecTypes['pg/int4@1']['output'] | null;
    quimica: CodecTypes['pg/text@1']['output'] | null;
    textura: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    valorPago: CodecTypes['pg/numeric@1']['output'];
    valorRevenda: CodecTypes['pg/numeric@1']['output'] | null;
    contato: public_Contato;
    readonly [RelationKeys]?: 'contato';
  };
  export type public_Contato = {
    cicloRecompraMeses: CodecTypes['pg/int4@1']['output'];
    cidadeId: CodecTypes['pg/uuid@1']['output'];
    comprimentoCm: CodecTypes['pg/int4@1']['output'] | null;
    cor: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    deletedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    endereco: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    motivoPerda: CodecTypes['pg/text@1']['output'] | null;
    natural: CodecTypes['pg/bool@1']['output'] | null;
    nome: CodecTypes['pg/text@1']['output'];
    observacoes: CodecTypes['pg/text@1']['output'] | null;
    origem: CodecTypes['pg/text@1']['output'] | null;
    quimica: CodecTypes['pg/text@1']['output'] | null;
    status: CodecTypes['pg/text@1']['output'];
    telefone: CodecTypes['pg/text@1']['output'] | null;
    textura: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    cidade: public_Cidade;
    compras: public_Compra[];
    fotos: public_Foto[];
    readonly [RelationKeys]?: 'cidade' | 'compras' | 'fotos';
  };
  export type public_Foto = {
    contatoId: CodecTypes['pg/uuid@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    ordem: CodecTypes['pg/int4@1']['output'];
    thumbUrl: CodecTypes['pg/text@1']['output'] | null;
    tipo: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    url: CodecTypes['pg/text@1']['output'];
    contato: public_Contato;
    readonly [RelationKeys]?: 'contato';
  };
}

export declare const models: {
  public: {
    Cidade: Models.public_Cidade;
    Compra: Models.public_Compra;
    Contato: Models.public_Contato;
    Foto: Models.public_Foto;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly cidades: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly lat: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly lng: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly uf: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nome', 'uf'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly compras: {
              columns: {
                readonly comprador: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly comprimento_cm: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly contato_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly cor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly data_corte: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly data_revenda: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly forma_pagamento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly peso_g: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly quimica: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly textura: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly valor_pago: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly valor_revenda: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'compras_contato_id_idx_f7fc9452';
                  readonly prefix: 'compras_contato_id_idx';
                  readonly columns: readonly ['contato_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'compras';
                    readonly columns: readonly ['contato_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'contatos';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly contatos: {
              columns: {
                readonly ciclo_recompra_meses: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 8>;
                  };
                };
                readonly cidade_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly comprimento_cm: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly cor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly deleted_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly endereco: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly motivo_perda: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly natural: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly observacoes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly origem: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly quimica: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'lead'>;
                  };
                };
                readonly telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly textura: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'contatos_cidade_id_idx_3c7827ff';
                  readonly prefix: 'contatos_cidade_id_idx';
                  readonly columns: readonly ['cidade_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'contatos_status_idx_e98638ab';
                  readonly prefix: 'contatos_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'contatos';
                    readonly columns: readonly ['cidade_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'cidades';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly fotos: {
              columns: {
                readonly contato_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly ordem: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly thumb_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'fotos_contato_id_idx_f7fc9452';
                  readonly prefix: 'fotos_contato_id_idx';
                  readonly columns: readonly ['contato_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fotos';
                    readonly columns: readonly ['contato_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'contatos';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly cidades: { readonly namespace: 'public' & NamespaceId; readonly model: 'Cidade' };
    readonly compras: { readonly namespace: 'public' & NamespaceId; readonly model: 'Compra' };
    readonly contatos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Contato' };
    readonly fotos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Foto' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Cidade: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly lat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly lng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly uf: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly contatos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Contato';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['cidadeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'cidades';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
                readonly nome: { readonly column: 'nome' };
                readonly uf: { readonly column: 'uf' };
              };
            };
          };
          readonly Compra: {
            readonly fields: {
              readonly comprador: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly comprimentoCm: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly contatoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly cor: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly dataCorte: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly dataRevenda: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly formaPagamento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly pesoG: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quimica: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly textura: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly valorPago: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly valorRevenda: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
            };
            readonly relations: {
              readonly contato: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Contato';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['contatoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'compras';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly comprador: { readonly column: 'comprador' };
                readonly comprimentoCm: { readonly column: 'comprimento_cm' };
                readonly contatoId: { readonly column: 'contato_id' };
                readonly cor: { readonly column: 'cor' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly dataCorte: { readonly column: 'data_corte' };
                readonly dataRevenda: { readonly column: 'data_revenda' };
                readonly formaPagamento: { readonly column: 'forma_pagamento' };
                readonly id: { readonly column: 'id' };
                readonly pesoG: { readonly column: 'peso_g' };
                readonly quimica: { readonly column: 'quimica' };
                readonly textura: { readonly column: 'textura' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly valorPago: { readonly column: 'valor_pago' };
                readonly valorRevenda: { readonly column: 'valor_revenda' };
              };
            };
          };
          readonly Contato: {
            readonly fields: {
              readonly cicloRecompraMeses: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cidadeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly comprimentoCm: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cor: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly deletedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly endereco: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly motivoPerda: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly natural: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly observacoes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly origem: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quimica: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly textura: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly cidade: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Cidade';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['cidadeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly compras: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Compra';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['contatoId'];
                };
              };
              readonly fotos: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Foto' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['contatoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'contatos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly cicloRecompraMeses: { readonly column: 'ciclo_recompra_meses' };
                readonly cidadeId: { readonly column: 'cidade_id' };
                readonly comprimentoCm: { readonly column: 'comprimento_cm' };
                readonly cor: { readonly column: 'cor' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly deletedAt: { readonly column: 'deleted_at' };
                readonly endereco: { readonly column: 'endereco' };
                readonly id: { readonly column: 'id' };
                readonly motivoPerda: { readonly column: 'motivo_perda' };
                readonly natural: { readonly column: 'natural' };
                readonly nome: { readonly column: 'nome' };
                readonly observacoes: { readonly column: 'observacoes' };
                readonly origem: { readonly column: 'origem' };
                readonly quimica: { readonly column: 'quimica' };
                readonly status: { readonly column: 'status' };
                readonly telefone: { readonly column: 'telefone' };
                readonly textura: { readonly column: 'textura' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Foto: {
            readonly fields: {
              readonly contatoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly ordem: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly thumbUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly contato: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Contato';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['contatoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'fotos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly contatoId: { readonly column: 'contato_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly ordem: { readonly column: 'ordem' };
                readonly thumbUrl: { readonly column: 'thumb_url' };
                readonly tipo: { readonly column: 'tipo' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly url: { readonly column: 'url' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'cidades';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'compras';
            readonly field: 'created_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'compras';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'compras';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'contatos';
            readonly field: 'created_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'contatos';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'contatos';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'fotos';
            readonly field: 'created_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'fotos';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'fotos';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
